### ISSUE TITLE
非常好的东西，我正式引入我的开源工程

### ISSUE THREAD

**Issue by freeeyes** [owt5008137/libiniloader#1]
非常好的东西，我正式引入我的开源工程
https://github.com/freeeyes/geohash
现在做C++的越来越少了，看了你的项目，很多很有创意。
也浏览了你的博客。
有机会的话互相学习和讨论技术的演进。

**Comment by owent** [comment]
@freeeyes 好呀好呀，你这个是LBS的东东？是只保存在共享内存还是会落地的？

**Comment by freeeyes** [comment]
会落地单车和车辆调度项目，4个省的，有机会加个微信吧，我的是41198969

发自我的 iPad

**Comment by owent** [comment]
@freeeyes 已加QQ，我的复杂点得项目大多集中在 https://github.com/xresloader 、 https://github.com/atframework 和 https://github.com/owent-utils 了
放在用户名下得项目其实都比较简单
